import { StyleSheet } from 'react-native'

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0F0F23' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 12,
  },
  title: { fontSize: 22, fontWeight: 'bold', color: '#FFDD00', letterSpacing: 2 },
  headerRight: { flexDirection: 'row' as const, gap: 8 },
  scoreBadge: {
    backgroundColor: '#1A1A2E', borderWidth: 2, borderColor: '#FFDD00',
    borderRadius: 6, paddingHorizontal: 10, paddingVertical: 4,
  },
  scoreText: { color: '#FFDD00', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  gameOverBadge: {
    backgroundColor: '#FF000030', borderWidth: 2, borderColor: '#FF0000',
    borderRadius: 6, paddingHorizontal: 10, paddingVertical: 4,
  },
  gameOverText: { color: '#FF4444', fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },
  modeRow: {
    flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 4,
  },
  modeButton: {
    paddingHorizontal: 16, paddingVertical: 6, borderRadius: 6,
    borderWidth: 2, borderColor: '#333366',
  },
  modeButtonActive: { backgroundColor: '#FFDD00', borderColor: '#CCAA00' },
  modeText: { color: '#666688', fontSize: 13, fontWeight: 'bold' },
  modeTextActive: { color: '#0F0F23' },
  inputRow: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 8, gap: 8 },
  input: {
    flex: 1, backgroundColor: '#1A1A2E', borderWidth: 2, borderColor: '#333366',
    borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10, color: '#FFFFFF', fontSize: 15,
  },
  addButton: {
    backgroundColor: '#FFDD00', borderRadius: 8, paddingHorizontal: 16,
    justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#CCAA00',
  },
  addButtonDisabled: { backgroundColor: '#333366', borderColor: '#222244' },
  addButtonText: { color: '#0F0F23', fontWeight: 'bold', fontSize: 13, letterSpacing: 1 },
  routineSection: { paddingHorizontal: 16, marginBottom: 8 },
  sectionLabel: { color: '#666688', fontSize: 11, fontWeight: 'bold', letterSpacing: 2, marginBottom: 6 },
  routineList: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  routineChip: {
    backgroundColor: '#1A1A2E', borderWidth: 1, borderColor: '#333366',
    borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4,
  },
  routineChipText: { color: '#AAAACC', fontSize: 12 },
  listContent: { paddingBottom: 100 },
  recordItem: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: '#1A1A2E',
  },
  numberBadge: {
    width: 32, height: 32, borderRadius: 16, backgroundColor: '#1A1A2E',
    borderWidth: 2, borderColor: '#333366', alignItems: 'center', justifyContent: 'center', marginRight: 12,
  },
  numberBadgeCompleted: { backgroundColor: '#00CC00', borderColor: '#009900' },
  numberText: { color: '#FFDD00', fontSize: 13, fontWeight: 'bold' },
  recordContent: { flex: 1 },
  recordText: { color: '#FFFFFF', fontSize: 15, fontWeight: '500' },
  recordTextCompleted: { color: '#666688', textDecorationLine: 'line-through' },
  recordDate: { color: '#666688', fontSize: 11, marginTop: 2, letterSpacing: 1 },
  blockBadge: { width: 36, height: 36, borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginLeft: 12 },
  blockText: { fontSize: 14, fontWeight: 'bold' },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyText: { color: '#666688', fontSize: 16, fontWeight: 'bold' },
  emptySubText: { color: '#444466', fontSize: 13, marginTop: 4 },
  fab: {
    position: 'absolute', bottom: 24, right: 20, width: 56, height: 56, borderRadius: 28,
    backgroundColor: '#FFDD00', alignItems: 'center', justifyContent: 'center',
    borderWidth: 3, borderColor: '#CCAA00', elevation: 8,
    shadowColor: '#FFDD00', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4,
  },
  fabText: { fontSize: 24 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.6)' },
  modalContent: {
    backgroundColor: '#0F0F23', borderTopLeftRadius: 20, borderTopRightRadius: 20,
    maxHeight: '70%', borderTopWidth: 3, borderLeftWidth: 2, borderRightWidth: 2,
    borderColor: '#333366', paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 2, borderBottomColor: '#1A1A2E',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFDD00', letterSpacing: 2 },
  modalClose: { color: '#666688', fontSize: 22, fontWeight: 'bold' },
  modalEmpty: { alignItems: 'center', paddingVertical: 40 },
  achievementItem: { paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#1A1A2E' },
  achievementHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  achievementLeft: { flex: 1 },
  achievementTitle: { color: '#FFDD00', fontSize: 14, fontWeight: 'bold', letterSpacing: 1 },
  achievementMeta: { color: '#666688', fontSize: 11, marginTop: 2 },
  achievementArrow: { color: '#666688', fontSize: 12, marginLeft: 8 },
  achievementBody: { marginTop: 10, paddingLeft: 4, borderLeftWidth: 2, borderLeftColor: '#333366', marginLeft: 2 },
  achievementRecordRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, paddingLeft: 8 },
  blockTypeBadge: {
    width: 28, height: 22, borderRadius: 4, backgroundColor: '#333366',
    alignItems: 'center', justifyContent: 'center', marginRight: 8,
  },
  blockTypeText: { color: '#FFDD00', fontSize: 11, fontWeight: 'bold' },
  achievementRecord: { color: '#AAAACC', fontSize: 13, flex: 1 },
})
