import { StyleSheet } from 'react-native'

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F8' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 12,
  },
  title: { fontSize: 22, fontWeight: 'bold', color: '#1A1A2E', letterSpacing: 2 },
  headerRight: { flexDirection: 'row' as const, gap: 8 },
  scoreBadge: {
    backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#FFBB00',
    borderRadius: 6, paddingHorizontal: 10, paddingVertical: 4,
  },
  scoreText: { color: '#CC8800', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  gameOverBadge: {
    backgroundColor: '#FFE0E0', borderWidth: 2, borderColor: '#FF4444',
    borderRadius: 6, paddingHorizontal: 10, paddingVertical: 4,
  },
  gameOverText: { color: '#CC0000', fontSize: 11, fontWeight: 'bold', letterSpacing: 1 },
  modeRow: {
    flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 4,
  },
  modeButton: {
    paddingHorizontal: 16, paddingVertical: 6, borderRadius: 6,
    borderWidth: 2, borderColor: '#D0D0E0',
  },
  modeButtonActive: { backgroundColor: '#1A1A2E', borderColor: '#1A1A2E' },
  modeText: { color: '#888899', fontSize: 13, fontWeight: 'bold' },
  modeTextActive: { color: '#FFFFFF' },
  inputRow: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 8, gap: 8 },
  input: {
    flex: 1, backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#D0D0E0',
    borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10, color: '#1A1A2E', fontSize: 15,
  },
  addButton: {
    backgroundColor: '#1A1A2E', borderRadius: 8, paddingHorizontal: 16,
    justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#0F0F23',
  },
  addButtonDisabled: { backgroundColor: '#D0D0E0', borderColor: '#BBBBCC' },
  addButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 13, letterSpacing: 1 },
  routineSection: { paddingHorizontal: 16, marginBottom: 8 },
  sectionLabel: { color: '#888899', fontSize: 11, fontWeight: 'bold', letterSpacing: 2, marginBottom: 6 },
  routineList: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  routineChip: {
    flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6,
    backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D0D0E0',
    borderRadius: 12, paddingLeft: 10, paddingRight: 4, paddingVertical: 4,
  },
  routineChipText: { color: '#555566', fontSize: 12 },
  routineDeleteButton: {
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: '#F0F0F5', alignItems: 'center' as const, justifyContent: 'center' as const,
  },
  routineDeleteText: { color: '#FF4444', fontSize: 11, fontWeight: 'bold' as const },
  listContent: { paddingBottom: 160 },
  recordItem: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: '#E8E8F0',
  },
  numberText: { color: '#1A1A2E', fontSize: 18, fontWeight: 'bold', marginRight: 14, minWidth: 22 },
  numberTextCompleted: { color: '#AAAABB' },
  recordContent: { flex: 1 },
  recordTextRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  recordText: { color: '#1A1A2E', fontSize: 15, fontWeight: '500', flexShrink: 1 },
  recordTextCompleted: { color: '#AAAABB', textDecorationLine: 'line-through' },
  routineIcon: { fontSize: 12 },
  dateHeader: {
    flexDirection: 'row' as const, alignItems: 'center' as const,
    paddingHorizontal: 16, paddingVertical: 10, gap: 10,
  },
  dateLine: { flex: 1, height: 1, backgroundColor: '#D0D0E0' },
  dateText: { color: '#888899', fontSize: 13, fontWeight: 'bold' },
  recordDate: { color: '#888899', fontSize: 11, marginTop: 2 },
  blockBadge: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', marginLeft: 12 },
  blockText: { fontSize: 14, fontWeight: 'bold' },
  pendingCheckbox: {
    width: 32, height: 32, borderWidth: 2, borderColor: '#FF4444',
    backgroundColor: 'transparent', marginLeft: 12,
    alignItems: 'center' as const, justifyContent: 'center' as const,
  },
  checkOverlay: { fontSize: 20, fontWeight: 'bold' as const, color: '#00CC00' },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyText: { color: '#888899', fontSize: 16, fontWeight: 'bold' },
  emptySubText: { color: '#AAAABB', fontSize: 13, marginTop: 4 },
  fab: {
    position: 'absolute', bottom: 24, right: 20, width: 56, height: 56, borderRadius: 28,
    backgroundColor: '#1A1A2E', alignItems: 'center', justifyContent: 'center',
    elevation: 8,
    shadowColor: '#000000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4,
  },
  fabText: { fontSize: 24 },
  modalOverlay: {
    flex: 1, justifyContent: 'center', alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalOverlayTouchable: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
  },
  modalContent: {
    backgroundColor: '#F5E6C8', borderRadius: 4, width: '85%', maxHeight: '70%',
    borderWidth: 3, borderColor: '#C4A882',
    shadowColor: '#000000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 10,
    overflow: 'hidden',
  },
  scrollHandle: {
    height: 14, backgroundColor: '#8B6914',
    borderTopWidth: 2, borderTopColor: '#A8841E',
  },
  scrollHandleBottom: {
    height: 14, backgroundColor: '#8B6914',
    borderBottomWidth: 2, borderBottomColor: '#6B5010',
  },
  modalHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: '#D4C4A0',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#5C3D10', letterSpacing: 2 },
  modalClose: { color: '#8B6914', fontSize: 22, fontWeight: 'bold' },
  modalEmpty: { alignItems: 'center', paddingVertical: 40 },
  emptyTextScroll: { color: '#8B7355', fontSize: 16, fontWeight: 'bold' },
  emptySubTextScroll: { color: '#A89878', fontSize: 13, marginTop: 4 },
  achievementItem: { paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#D4C4A0' },
  achievementHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  achievementLeft: { flex: 1 },
  achievementTitle: { color: '#5C3D10', fontSize: 14, fontWeight: 'bold', letterSpacing: 1 },
  achievementMeta: { color: '#8B7355', fontSize: 11, marginTop: 2 },
  achievementArrow: { color: '#8B7355', fontSize: 12, marginLeft: 8 },
  achievementBody: { marginTop: 10, paddingLeft: 4, borderLeftWidth: 2, borderLeftColor: '#D4C4A0', marginLeft: 2 },
  achievementRecordRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, paddingLeft: 8 },
  blockTypeBadge: {
    width: 28, height: 22, borderRadius: 4, backgroundColor: '#E8E8F0',
    alignItems: 'center', justifyContent: 'center', marginRight: 8,
  },
  blockTypeText: { color: '#1A1A2E', fontSize: 11, fontWeight: 'bold' },
  blockColorDot: {
    width: 14, height: 14, marginRight: 8,
    borderTopWidth: 2, borderLeftWidth: 2, borderTopColor: 'rgba(255,255,255,0.4)', borderLeftColor: 'rgba(255,255,255,0.4)',
    borderBottomWidth: 2, borderRightWidth: 2, borderBottomColor: 'rgba(0,0,0,0.3)', borderRightColor: 'rgba(0,0,0,0.3)',
  },
  achievementRecord: { color: '#5C4A2A', fontSize: 13, flex: 1 },
})
